pub mod create_page;
pub mod create_with_set_form;
pub mod delete_page;
pub mod detail_page;
pub mod exercise_per_movement;
pub mod model;
#[cfg(feature = "ssr")]
pub mod repository_impl;
pub mod update_page;
