pub mod activity_level;
pub mod component;
pub mod create_page;
pub mod delete_page;
pub mod detail_page;
pub mod detail_table;
pub mod fitness_goal;
pub mod model;
#[cfg(feature = "ssr")]
pub mod permission;
pub mod profile_image;
#[cfg(feature = "ssr")]
pub mod repository_impl;
pub mod sex;
pub mod update_page;
pub mod upload_page;
#[cfg(feature = "ssr")]
pub mod validate;
