pub mod add_food_page;
pub mod add_meal_page;
pub mod component;
pub mod copy_previous_day_form;
pub mod copy_previous_meal_form;
pub mod day_page;
pub mod delete_page;
pub mod detail_page;
pub mod model;
#[cfg(feature = "ssr")]
pub mod permission;
#[cfg(feature = "ssr")]
pub mod repository_impl;
pub mod router;
#[cfg(feature = "ssr")]
pub mod service;
pub mod to_meal_form;
pub mod update_page;
#[cfg(feature = "ssr")]
pub mod validate;
pub mod week_navigation;
