pub mod component;
pub mod create_page;
pub mod delete_page;
pub mod detail_page;
pub mod detail_table;
pub mod from_profile_form;
pub mod list_page;
pub mod model;
#[cfg(feature = "ssr")]
pub mod permission;
#[cfg(feature = "ssr")]
pub mod repository_impl;
#[cfg(feature = "ssr")]
pub mod service;
pub mod update_or_create_form;
pub mod update_page;
#[cfg(feature = "ssr")]
pub mod validate;
